checkpoints:
  checkpoint_interval: 100
  checkpoints_path: checkpoints/qwen2_moe_baseline_100step
  checkpoints_path_is_shared_file_system: false
  load_lr_scheduler: true
  load_optimizer: true
  resume_checkpoint_path: null
  save_final_state: true
  save_initial_state: false

data_stages:
- data:
    dataset: null
    num_loading_workers: 1
    seed: 42
  name: dummy
  start_training_step: 1

general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: true
  project: qwen2_moe_smoke
  run: qwen2_moe_baseline_100step_%date_%jobid
  seed: 42
  step: null

lighteval: null

logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info

metrics_logging: null

model:
  ddp_bucket_cap_mb: 25
  dtype: bfloat16
  init_method:
    std: 0.025
  make_vocab_size_divisible_by: 1
  model_config:
    _attn_implementation: flash_attention_2
    _fused_rms_norm: true
    _fused_rotary_emb: true
    _use_doc_masking: true
    _use_qkv_packed: true
    attention_bias: false
    bos_token_id: 1
    eos_token_id: 2
    flex_attention_mask: null
    hidden_act: silu
    hidden_size: 128
    initializer_range: 0.02
    intermediate_size: 512
    is_qwen2_config: true
    max_position_embeddings: 128
    moe_config:
      enable_shared_expert: true
      layers:
      - 0
      - 1
      moe_intermediate_size: 256
      num_experts: 4
      router_aux_loss_coef: 0.01
      shared_expert_intermediate_size: 512
      token_dispatcher_type: alltoall
      top_k: 1
    no_rope_layer: null
    num_attention_heads: 4
    num_hidden_layers: 2
    num_key_value_heads: 4
    pad_token_id: null
    pretraining_tp: 1
    rms_norm_eps: 1.0e-06
    rope_interleaved: false
    rope_scaling: null
    rope_seq_len_interpolation_factor: null
    rope_theta: 10000.0
    sliding_window_size: null
    tie_word_embeddings: false
    use_cache: true
    vocab_size: 4096
    z_loss_coefficient: 0.0001
    z_loss_enabled: false

optimizer:
  accumulate_grad_in_fp32: true
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 0.0003
    lr_decay_starting_step: null
    lr_decay_steps: 99
    lr_decay_style: cosine
    lr_warmup_steps: 1
    lr_warmup_style: linear
    min_decay_lr: 1.0e-05
  optimizer_factory:
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    name: adamW
    torch_adam_is_fused: false
  weight_decay: 0.01
  weight_decay_exclude_named_params: []
  zero_stage: 0

parallelism:
  context_parallel_size: 1
  dp: 1
  expert_parallel_size: 1
  pp: 1
  pp_engine: 1f1b
  recompute_layer: false
  tp: 1
  tp_linear_async_communication: false
  tp_mode: ALL_REDUCE
  tp_recompute_allgather: true

profiler: null
s3_upload: null

tokenizer:
  tokenizer_max_length: null
  tokenizer_name_or_path: null
  tokenizer_revision: null

tokens:
  batch_accumulation_per_replica: 1
  limit_test_batches: 0
  limit_val_batches: 0
  micro_batch_size: 2
  sequence_length: 128
  train_steps: 100
  val_check_interval: -1
